### ISSUE TITLE
Plugin have error

### ISSUE THREAD

**Issue by lDavidMC** [Muqsit/FaceLogin#11]
19.06 22:31:46 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'FaceLogin v1.1.0': Call to undefined method pocketmine\Server::getAsyncPool() on Muqsit\FaceLogin 19.06 22:31:46 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\Server::getAsyncPool()" (EXCEPTION) in "FaceLogin.phar/src/Muqsit/FaceLogin" at line 71 19.06 22:31:46 [Server] Server thread/DEBUG #0 FaceLogin.phar/src/Muqsit/FaceLogin(77): Muqsit\FaceLogin->sendFace(pocketmine\Player object) 19.06 22:31:46 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/MethodEventExecutor(38): Muqsit\FaceLogin->onJoin(pocketmine\event\player\PlayerJoinEvent object) 19.06 22:31:46 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(Muqsit\FaceLogin object, pocketmine\event\player\PlayerJoinEvent object) 19.06 22:31:46 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(701): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerJoinEvent object) 19.06 22:31:46 [Server] Server thread/DEBUG #4 src/pocketmine/Player(1028): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerJoinEvent object) 19.06 22:31:46 [Server] Server thread/DEBUG #5 src/pocketmine/Player(976): pocketmine\Player->doFirstSpawn() 19.06 22:31:46 [Server] Server thread/DEBUG #6 src/pocketmine/level/Level(2453): pocketmine\Player->sendChunk(integer 14, integer 19, pocketmine\network\mcpe\protocol\BatchPacket object) 19.06 22:31:46 [Server] Server thread/DEBUG #7 src/pocketmine/level/Level(2498): pocketmine\level\Level->sendChunkFromCache(integer 14, integer 19) 19.06 22:31:46 [Server] Server thread/DEBUG #8 src/pocketmine/level/format/io/ChunkRequestTask(88): pocketmine\level\Level->chunkRequestCallback(integer 14, integer 19, pocketmine\network\mcpe\protocol\BatchPacket object) 19.06 22:31:46 [Server] Server thread/DEBUG #9 src/pocketmine/scheduler/AsyncPool(172): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object) 19.06 22:31:46 [Server] Server thread/DEBUG #10 src/pocketmine/scheduler/ServerScheduler(264): pocketmine\scheduler\AsyncPool->collectTasks() 19.06 22:31:46 [Server] Server thread/DEBUG #11 src/pocketmine/Server(2525): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 373) 19.06 22:31:46 [Server] Server thread/DEBUG #12 src/pocketmine/Server(2276): pocketmine\Server->tick() 19.06 22:31:46 [Server] Server thread/DEBUG #13 src/pocketmine/Server(2150): pocketmine\Server->tickProcessor() 19.06 22:31:46 [Server] Server thread/DEBUG #14 src/pocketmine/Server(1733): pocketmine\Server->start() 19.06 22:31:46 [Server] Server thread/DEBUG #15 src/pocketmine/PocketMine(290): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/) 19.06 22:31:46 [Server] Server thread/DEBUG #16 /pmmp_1079_1.4.0.phar(1): require(string phar:///pmmp_1079_1.4.0.phar/src/pocketmine/PocketMine.php)

**Comment by Muqsit** [comment]
You are using an outdated version of FaceLogin

**Comment by Muqsit** [comment]
You're running an outdated version of PocketMine

**Comment by lDavidMC** [comment]
Sure?
PocketMine-MP 1.7dev-1079 「[REDACTED]」 implementing API version 3.0.0-ALPHA12 for Minecraft: PE v1.4.0 (protocol version 261)

**Comment by Muqsit** [comment]
Yeah, sure.

**Comment by lDavidMC** [comment]
What is the latest version

**Comment by Muqsit** [comment]
https://github.com/pmmp/PocketMine-MP/releases

**Comment by lDavidMC** [comment]
Ok thanks, sorry for my ignorance
