### ISSUE TITLE
sqrt not needed?

### ISSUE THREAD

**Issue by legoboy0215** [Muqsit/FaceLogin#2]
https://github.com/Muqsit/FaceLogin/blob/master/src/Muqsit/SendPlayerFaceTask.php#L93

The sqrt might not be needed, as it is comparing the difference instead of using the actual value.

**Comment by Muqsit** [comment]
Yeah 👍

**Comment by BrianZP** [comment]
Thanks alot @Muqsit for this awesome plugin.
