### ISSUE TITLE
add new things

### ISSUE THREAD

**Issue by ghost** [Muqsit/FaceLogin#5]
add body, legs and foot

**Comment by Muqsit** [comment]
"Face" login

**Comment by ghost** [comment]
can you make a plugin that shows all player's skin?

**Comment by Muqsit** [comment]
@ExaSonit I can't. All the code here is written by Legoboy. I've only made his code run asynchronously to avoid any tick loss.

**Comment by ghost** [comment]
can you ask this at legoboy?

**Comment by Muqsit** [comment]
You can ask Legoboy

**Comment by ExaSonit** [comment]
how can i contact legoboy?

**Comment by ghost** [comment]
ok, i did it

**Comment by legoboy0215** [comment]
I don't have time to do this stuff lol
