### ISSUE TITLE
Error when a player joins

### ISSUE THREAD

**Issue by ghost** [Muqsit/FaceLogin#8]
[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'FaceLogin v1.0.0': Call to undefined method pocketmine\Player::getSkinData() on Muqsit\FaceLogin
[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Player::getSkinData()" (EXCEPTION) in "FaceLogin-master/src/Muqsit/FaceLogin" at line 71

**Comment by CortexPE** [comment]
The PMMP Plugin API has been updated... Thus affecting how skin data is retrieved from the player.
